server:
	 kitex -I ../../idl/ -type protobuf -module example -service comment  ../../idl/comment.proto

reserver:
	  kitex -I ../../idl/ -type protobuf -module example -service a.b.c  ../../idl/comment.proto