// Code generated by Kitex v0.3.1. DO NOT EDIT.

package videoservice

import (
	"context"
	"example/cmd/video/kitex_gen/video"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateVideo(ctx context.Context, Req *video.CreateVideoRequest, callOptions ...callopt.Option) (r *video.CreateVideoResp, err error)
	GetVideoFeed(ctx context.Context, Req *video.GetVideoFeedRequest, callOptions ...callopt.Option) (r *video.GetVideoFeedResp, err error)
	GetPublishList(ctx context.Context, Req *video.GetPublishListRequest, callOptions ...callopt.Option) (r *video.GetPublishListResp, err error)
	AddFavorite(ctx context.Context, Req *video.AddFavoriteRequest, callOptions ...callopt.Option) (r *video.AddFavoriteResp, err error)
	RmFavorite(ctx context.Context, Req *video.RmFavoriteRequest, callOptions ...callopt.Option) (r *video.RmFavoriteResp, err error)
	FavoriteVideo(ctx context.Context, Req *video.FavoriteVideoRequest, callOptions ...callopt.Option) (r *video.FavoriteVideoResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kVideoServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kVideoServiceClient struct {
	*kClient
}

func (p *kVideoServiceClient) CreateVideo(ctx context.Context, Req *video.CreateVideoRequest, callOptions ...callopt.Option) (r *video.CreateVideoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateVideo(ctx, Req)
}

func (p *kVideoServiceClient) GetVideoFeed(ctx context.Context, Req *video.GetVideoFeedRequest, callOptions ...callopt.Option) (r *video.GetVideoFeedResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetVideoFeed(ctx, Req)
}

func (p *kVideoServiceClient) GetPublishList(ctx context.Context, Req *video.GetPublishListRequest, callOptions ...callopt.Option) (r *video.GetPublishListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPublishList(ctx, Req)
}

func (p *kVideoServiceClient) AddFavorite(ctx context.Context, Req *video.AddFavoriteRequest, callOptions ...callopt.Option) (r *video.AddFavoriteResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddFavorite(ctx, Req)
}

func (p *kVideoServiceClient) RmFavorite(ctx context.Context, Req *video.RmFavoriteRequest, callOptions ...callopt.Option) (r *video.RmFavoriteResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RmFavorite(ctx, Req)
}

func (p *kVideoServiceClient) FavoriteVideo(ctx context.Context, Req *video.FavoriteVideoRequest, callOptions ...callopt.Option) (r *video.FavoriteVideoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FavoriteVideo(ctx, Req)
}
