server:
	 kitex -I ../../idl/ -type protobuf -module example -service video  ../../idl/video.proto

reserver:
	  kitex -I ../../idl/ -type protobuf -module example -service a.b.c  ../../idl/video.proto