// Code generated by Kitex v0.3.1. DO NOT EDIT.

package commentservice

import (
	"context"
	"example/cmd/comment/kitex_gen/comment"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	AddComment(ctx context.Context, Req *comment.AddCommentRequest, callOptions ...callopt.Option) (r *comment.AddCommentResp, err error)
	DelComment(ctx context.Context, Req *comment.DelCommentRequest, callOptions ...callopt.Option) (r *comment.DelCommentResp, err error)
	GetCommentCount(ctx context.Context, Req *comment.GetCommentCountRequest, callOptions ...callopt.Option) (r *comment.GetCommentCountResp, err error)
	GetCommentList(ctx context.Context, Req *comment.GetCommentListRequest, callOptions ...callopt.Option) (r *comment.GetCommentListResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kCommentServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCommentServiceClient struct {
	*kClient
}

func (p *kCommentServiceClient) AddComment(ctx context.Context, Req *comment.AddCommentRequest, callOptions ...callopt.Option) (r *comment.AddCommentResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddComment(ctx, Req)
}

func (p *kCommentServiceClient) DelComment(ctx context.Context, Req *comment.DelCommentRequest, callOptions ...callopt.Option) (r *comment.DelCommentResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DelComment(ctx, Req)
}

func (p *kCommentServiceClient) GetCommentCount(ctx context.Context, Req *comment.GetCommentCountRequest, callOptions ...callopt.Option) (r *comment.GetCommentCountResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCommentCount(ctx, Req)
}

func (p *kCommentServiceClient) GetCommentList(ctx context.Context, Req *comment.GetCommentListRequest, callOptions ...callopt.Option) (r *comment.GetCommentListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCommentList(ctx, Req)
}
